#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Dame una Pista!!!

# Short bio or description (displayed in the header)
description: Un camino, una vía para hacer y aprender.
# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: https://xolagl2.github.io/images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: socialgl2-blogs@yahoo.com
  facebook:
  flickr:
  github: xolagl2
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCqv-3xds1qv7CyrBDg1C70w?view_as=subscriber # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://xolagl2.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

defaults:
    - scope:
        path: _posts
        type: posts
      values:
        layout: post
        author: J.R. Galindo A.
        #permalink: /:categories/:title.html
    - scope:
        path: ""
        type: pages
      values:
        layout: page
        author: J.R. Galindo A.
        #permalink: /:title.html
    - scope:
        path: _drafts
      values:
        layout: post
        comments: false

collections:
  drafts:
    output: true

# To use Utterance comments,  you can going to https://utteranc.es/ get more parameters interpretation.
utterance:
  # Note: Make sure the repo is public, otherwise your readers will not be able to view the issues/comments.
  # Make sure the [utterances app](https://github.com/apps/utterances) is installed on the repo, otherwise users will not be able to post comments.
  #  If your repo is a fork, navigate to it's settings tab and confirm the issues feature is turned on.
  repo:  xolagl2/xolagl2.github.io # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: title   # Choose the mapping between blog posts and GitHub issues. 
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default

  ## Optional
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.